### ISSUE TITLE
記事中のリポジトリへのリンクに誤りがあります

### ISSUE THREAD

**Issue by shin-g** [CentRa-Linux/zenn#1]
[新しいデスクトップ環境、NuDesktopについての技術的解説+α](https://github.com/CentRa-Linux/zenn/blob/master/articles/nudesktop-mitou-jr.md)   

記事も動画も楽しく拝見しました。  
開発の進展を楽しみにしています。

挙げられているリポジトリのリンクが誤っているようです。

正: https://github.com/CentRa-Linux/NuDesktop_Shell  
誤: https://github.com/CentRa-Linux/NuDesktop-Shell

ご確認ください。

**Comment by CentRa-Linux** [comment]
確認しました。ありがとうございます。
